fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "datacat": "https://github.com/richardc/puppet-datacat.git"
  symlinks:
    "goaudit": "#{source_dir}"

