---
language: ruby
sudo: false
# Delete dependency locks for matrix builds.
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 2.0.0
  - 2.1.0
  - 2.4.3
env:
  - PUPPET_VERSION="~> 5.1.0"
